### ISSUE TITLE
expose memory and WASI?

### ISSUE THREAD

**Issue by codefromthecrypt** [birros/go-wasm3#5]
wondering if it isn't too much trouble to export functions to write memory and enable WASI?

Besides WASI, I'd like to implement this signature (even knowing wasm3 isn't context-aware). Other memory ops aren't so needed. This is only for comparison purposes.

```
func (m *wasm3Module) WriteMemory(_ context.Context, offset uint32, bytes []byte) error {
```

**Comment by birros** [comment]
I understand the need, but I really don't have time to spend on it, sorry.

If you need these functions only to benchmark and compare with [wazero](https://github.com/tetratelabs/wazero) I advise you to implement your benchmark directly in c, golang doesn't bring any real overhead and is therefore negligible in this case. It will avoid you to spend time to make a binding in go only for this purpose.

Another important advantage, you will get results much closer to the performance of the current version of [wasm3](https://github.com/wasm3/wasm3), since the known go bindings, this one and [matiasinsaurralde/go-wasm3](https://github.com/matiasinsaurralde/go-wasm3), are outdated.

I think this is the best option in this case. Otherwise, you write your benchmark in a single c function that you call with cgo.

Sorry 🙂
